site_name: 未央学习

repo_url: https://github.com/WeiYangXueXi/WeiYangXueXi.github.io
repo_name: WeiYangXueXi

theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    logo: material/file-document
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation
    - navigation.top
    - navigation.sections 
    - navigation.tracking


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

plugins:
  - glightbox
  - search

extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_javascript:
  - custom_js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - custom_css/extra.css

  

nav:
  - 首页:
      - 欢迎来到未央学习: "index.md"
      - 读者须知: "reader.md"
      - 加入我们！: "author.md"
  - 选课指南:
      - 介绍: "course_selection/index.md"
      - 思政篇: "course_selection/politics/index.md"
      - 化生篇: "course_selection/chem_bio/index.md"
      - 数理篇: "course_selection/math_phys/index.md"
      - 工信篇: "course_selection/engineer_info/index.md"
      - 英语篇: "course_selection/english/index.md"
      - 体育篇: "course_selection/pe/index.md"
      - 通识篇: "course_selection/general/index.md"
  - 课程指引:
      - 介绍: "courses/index.md"
      - 基础课:
          - 数学类: 
              - 微积分: "courses/basic/maths/calculus/index.md"
              - 线性代数: "courses/basic/maths/linear_algebra/index.md"
              - 复变函数:
                  - 介绍: "courses/basic/maths/complex_func/index.md"
                  - 作业答案:
                    - 主页: "courses/basic/maths/complex_func/hw_ans/index.md"
                    - hw_1: "courses/basic/maths/complex_func/hw_ans/hw_1.md"
                    - hw_2: "courses/basic/maths/complex_func/hw_ans/hw_2.md"
                    - hw_3: "courses/basic/maths/complex_func/hw_ans/hw_3.md"
                    - hw_4: "courses/basic/maths/complex_func/hw_ans/hw_4.md"
                    - hw_5: "courses/basic/maths/complex_func/hw_ans/hw_5.md"
                    - hw_6: "courses/basic/maths/complex_func/hw_ans/hw_6.md"
                    - hw_7: "courses/basic/maths/complex_func/hw_ans/hw_7.md"
                    - hw_8: "courses/basic/maths/complex_func/hw_ans/hw_8.md"
                    - hw_9: "courses/basic/maths/complex_func/hw_ans/hw_9.md"
                    - hw_10: "courses/basic/maths/complex_func/hw_ans/hw_10.md"
                    - hw_11: "courses/basic/maths/complex_func/hw_ans/hw_11.md"
              - 数学物理方程: "courses/basic/maths/mathematical_physics_equations/index.md"
              - 概率论: "courses/basic/maths/probability/index.md"
          - 物理类: 
              - 基础物理学: "courses/basic/physics/fundamental_physics/index.md"
              - 量子力学(1): "courses/basic/physics/quantum_mechanics/index.md"
          - 实验类:
              - 物理实验: "courses/basic/labs/lab_of_physics/index.md"
          - 思政类:
              - 马克思主义基本原理: "courses/basic/politics/basic_principles_of_marxism/index.md"
          - 化生类:
              - 现代生物学导论: "courses/basic/chem_bio/intro_to_modern_biology/index.md"
              - 大学化学B: "courses/basic/chem_bio/university_chemistry_b/index.md"
              - 物理化学B: "courses/basic/chem_bio/physical_chemistry_b/index.md"
          - 工程/信息基础课程:
              - 离散数学: "courses/basic/engineer_info/discrete_mathematics/index.md"
              - 离散数学(2): "courses/basic/engineer_info/discrete_mathematics_2/index.md"
              - 程序设计基础:
                - 主页: "courses/basic/engineer_info/programming/index.md"
                - Python 程序设计笔记: "courses/basic/engineer_info/programming/note_py.md"
                - C++ 程序设计笔记: "courses/basic/engineer_info/programming/note_cpp.md"
              - 工程图学基础/机械设计基础(1): "courses/basic/engineer_info/fundamentals_of_engineering_graphics/index.md"
      - 专业课:
          - 数学类: 
              - 常微分方程: "courses/professional/maths/ordinary_differential_equation/index.md"
              - 高等线性代数选讲（英）: "courses/professional/maths/advanced_algebra_selected/index.md"
              - 基础拓扑学: "courses/professional/maths/fundamental_topology/index.md"
              - 高等微积分:
                - 介绍: "courses/professional/maths/advanced_calculus/index.md"
                - hw_1: "courses/professional/maths/advanced_calculus/ans/hw_1.md"
                - hw_2: "courses/professional/maths/advanced_calculus/ans/hw_2.md"
                - hw_3: "courses/professional/maths/advanced_calculus/ans/hw_3.md"
                - hw_4: "courses/professional/maths/advanced_calculus/ans/hw_4.md"
                - hw_5: "courses/professional/maths/advanced_calculus/ans/hw_5.md"
                - hw_6: "courses/professional/maths/advanced_calculus/ans/hw_6.md"
                - hw_7: "courses/professional/maths/advanced_calculus/ans/hw_7.md"
                - hw_8: "courses/professional/maths/advanced_calculus/ans/hw_8.md"
                - hw_9: "courses/professional/maths/advanced_calculus/ans/hw_9.md"
                - hw_10: "courses/professional/maths/advanced_calculus/ans/hw_10.md"
          - 物理类: 
              - 统计力学: "courses/professional/physics/statistical_mechanics/index.md"
              - 电动力学: 
                 - 介绍: "courses/professional/physics/electrodynamics/index.md"
                 - hw_2: "courses/professional/physics/electrodynamics/hw_ans/hw_2.md"
                 - hw_3: "courses/professional/physics/electrodynamics/hw_ans/hw_3.md"
                 - hw_4: "courses/professional/physics/electrodynamics/hw_ans/hw_4.md"
                 - hw_5: "courses/professional/physics/electrodynamics/hw_ans/hw_5.md"
                 - hw_6: "courses/professional/physics/electrodynamics/hw_ans/hw_6.md"
                 - hw_7: "courses/professional/physics/electrodynamics/hw_ans/hw_7.md"
                 - hw_8: "courses/professional/physics/electrodynamics/hw_ans/hw_8.md"
                 - hw_9: "courses/professional/physics/electrodynamics/hw_ans/hw_9.md"
                 - hw_10: "courses/professional/physics/electrodynamics/hw_ans/hw_10.md"
                 - hw_12: "courses/professional/physics/electrodynamics/hw_ans/hw_12.md"
                 - hw_13: "courses/professional/physics/electrodynamics/hw_ans/hw_13.md"
                 - hw_14: "courses/professional/physics/electrodynamics/hw_ans/hw_14.md"
                 - hw_15: "courses/professional/physics/electrodynamics/hw_ans/hw_15.md"
          - 电类:
              - 电路原理: "courses/professional/electricity/principles_of_circuits/index.md"
              - 电工与电子技术: "courses/professional/electricity/electrical_and_electronic_technology/index.md"
              - 电力电子技术: "courses/professional/electricity/power_electronics/index.md"
          - 材料类:
              - 材料科学基础: "courses/professional/materials/funda_of_materials_science/index.md"
              - 工程材料: "courses/professional/materials/engineering_materials/index.md"
          - 计算类:
              - 计算机原理与应用: "courses/professional/computing/princ_and_app_of_computer/index.md"
              - 动力建模与仿真: "courses/professional/computing/dynamic_modeling_and_simulation/index.md"
          - 能源类:
              - 储能技术: "courses/professional/energy/energy_storage_technology/index.md"
              - 先进燃气轮机理论与实验技术: "courses/professional/energy/gas_turbine_theory/index.md"
          - 机械类: 
              - 机械设计基础 B(3): "courses/professional/mechanics/mechnical_design_b3/index.md"
          - 土木类:
              - 工程经济学: "courses/professional/civil/engineering_economics/index.md"
      - 通识选修课:
          - 经济学原理: "courses/general/principles_of_economics/index.md"
          - 《庄子》导读: "courses/general/zhuangzi_guide/index.md"
  - 技能培训:
      - 介绍: "skills/index.md"
      - mkdocs：搭建一个属于你的小网站: "skills/mkdocs.md"
      - Markdown：无纸化学习必备: "skills/markdown.md"
      - EndNote： 你的宝藏文献管理工具: "skills/endnote.md"
      - MATLAB 讲座: "skills/matlab.md"
      - LaTeX 讲座: "skills/latex.md"
      - R语言使用指南: "skills/R.md"
  - 资源链接:
      - 介绍: "resources/index.md"
      - 乐学资源: "resources/lexue/index.md"
  - 资源共享:
      - 学习资料共享计划: "sharing/contribution.md"
  - 未央活动:
      - 介绍: "activities/index.md"
